language: php

php:
   - "7.2"
   #- "7.3"
   #- hhvm
   #- nightly

matrix:
    allow_failures:
        - php: nightly
        - php: hhvm

services:
  - docker

sudo: false

git:
    submodules: false

before_script:
    - make install check

script:
    - make docker COMMAND="make build solve"
    - make docker COMMAND="make test"

notifications:
    irc: "irc.freenode.org#dbwebb"

    webhooks:
        urls:
            - https://webhooks.gitter.im/e/7db2bbd18730e2d4c2cb
        # options: [always|never|change] default: always
        on_success: change
        on_failure: always
        on_start: never
